version: '3.1'

services:

  api:
    image: mario21ic/dmc-api:latest
    build:
      context: ./
    volumes:
      - ./src/:/apps/
    environment:
      FLASK_APP: api.py
    command: ["flask", "run", "-h", "0.0.0.0", "-p", "8080"]
    ports:
      - 8080:8080

