version: '3.1'

services:

  api:
    image: mario21ic/dmc-api:latest
    build:
      context: ./
    volumes:
      - ./src/:/apps/
    environment:
      FLASK_APP: manage.py
    command: ["flask", "db", "init"]

