version: '3.1'
services:
  api:
    image: francisjosue/dmc-api:latest
    build:
      context: ./
    volumes:
      - ./:/app/
    environment:
      FLASK_APP: src/api.py
    command: ["flask", "run", "-h", "0.0.0.0", "-p", "8080"]
#    command: ["./start.sh"]
    ports:
      - 8081:8080
